version: "3.1"

services:
    mongodb:
        container_name: mongoDB
        image: mongo:latest
        restart: always
        volumes:
          # - ./db/study1:/data/db
          - ./db/surveyDBData:/data/db
        environment:
          - MONGO_INITDB_DATABASE=Survey
        ports:
          - 27017:27017
    api:
        container_name: lta-api
        image: uoy/lta-api:latest
        depends_on:
          - 'mongodb'
        restart: always
        ports:
          - 9001:9001
    webapp:
        container_name: lta-webapp
        image: uoy/lta-webapp:latest
        depends_on:
          - 'api'
        restart: always
        volumes:
          - ./cert:/etc/ssl
        ports:
          - 80:80
          - 443:443